import { QuioscoProvider } from "@/context/QuioscoProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cafeteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QuioscoProvider>
          <div id="__next">{children}</div>
        </QuioscoProvider>
      </body>
    </html>
  );
}
